support tlcp
Tongsuo-Project/tongsuo-java-sdk pull request #12
Opened 2023-01-30 05:05 UTC by superajun-wsj

2023-02-07 09:20 UTC, dongbeiouba requested changes
缺少测试用例。包括
- TLCP 密码套件协商
- TLCP SNI
- TLCP ALPN
- TLCP session复用

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    if (sslCtx.get() == nullptr) {
判空位置不对，SSL_CTX_new()之后，SSL_CTX_enable_ntls()前判断。

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +            if (sk_X509_push(chain.get(), x509.get()) <= 0)
证书放到chain后，没有使用chain？

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +            if (sk_X509_push(chain.get(), x509.get()) <= 0)
证书放到chain后，没有使用chain？

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/main/java/org/conscrypt/NativeCrypto.java
> +            "ECC-SM2-WITH-SM4-SM3",
套件少，需要补齐

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/main/java/org/conscrypt/NativeCrypto.java
> +    static native void setGMSignLocalCertsAndPrivateKey(long ssl, NativeSsl ssl_holder, byte[][] encodedCertificates,
名字里面没必要加GM

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/main/java/org/conscrypt/NativeCrypto.java
> +    static native void setGMEncLocalCertsAndPrivateKey(long ssl, NativeSsl ssl_holder, byte[][] encodedCertificates,
名字里面没必要加GM

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/main/java/org/conscrypt/SSLUtils.java
> +            System.getProperty("org.conscrypt.useEngineSocketByDefault", "false"));
这里为啥改成false？

2023-02-07 09:20 UTC, dongbeiouba commented on common/src/test/java/org/conscrypt/ConscryptSuite.java
> +        // SSLSocketVersionCompatibilityTest.class,
为啥删除？

2023-02-07 09:20 UTC, dongbeiouba commented on testing/src/main/java/org/conscrypt/javax/net/ssl/SSLConfigurationAsserts.java
> +        // StandardNames.assertSupportedProtocols(supportedParameters.getProtocols());
为啥删除？

2023-02-13 08:16 UTC, superajun-wsj commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    if (sslCtx.get() == nullptr) {
Done

2023-02-13 08:28 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SSLUtils.java
> +            System.getProperty("org.conscrypt.useEngineSocketByDefault", "false"));
tlcp异步模式跑不通，目前只有同步模式可以work。

2023-02-20 14:22 UTC, superajun-wsj commented on CAPABILITIES.md
> +  * `ECC-SM2-WITH-SM4-SM3`
RSA-SM4-CBC-SM3、RSA-SM4-GCM-SM3、RSA-SM4-CBC-SHA256、RSA-SM4-GCM-SHA256放到下个patch再实现，这个patch优先解决ECC-SM2-SM4-CBC-SM3、ECC-SM2-SM4-GCM-SM3、ECDHE-SM2-SM4-CBC-SM3、ECDHE-SM2-SM4-GCM-SM3

2023-02-20 14:26 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/NativeCrypto.java
> +    static native void setGMSignLocalCertsAndPrivateKey(long ssl, NativeSsl ssl_holder, byte[][] encodedCertificates,
Done

2023-02-20 14:27 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/NativeCrypto.java
> +    static native void setGMEncLocalCertsAndPrivateKey(long ssl, NativeSsl ssl_holder, byte[][] encodedCertificates,
Done

2023-02-20 14:27 UTC, superajun-wsj commented on common/src/test/java/org/conscrypt/ConscryptSuite.java
> +        // SSLSocketVersionCompatibilityTest.class,
fixed

2023-02-20 14:27 UTC, superajun-wsj commented on testing/src/main/java/org/conscrypt/javax/net/ssl/SSLConfigurationAsserts.java
> +        // StandardNames.assertSupportedProtocols(supportedParameters.getProtocols());
fixed

2023-02-21 04:00 UTC, superajun-wsj commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +            if (sk_X509_push(chain.get(), x509.get()) <= 0)
Done

2023-02-21 04:00 UTC, superajun-wsj commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +            if (sk_X509_push(chain.get(), x509.get()) <= 0)
Done

2023-02-22 03:55 UTC, superajun-wsj commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +void configure_ssl_ctx(SSL_CTX* ssl_ctx, bool isClientMode, bool flag) {
Done

2023-02-24 23:19 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/NativeCrypto.java
> +            "ECC-SM2-WITH-SM4-SM3",
Done

2023-02-24 23:24 UTC, superajun-wsj commented
> 缺少测试用例。包括
> 
> * TLCP 密码套件协商
> * TLCP SNI
> * TLCP ALPN
> * TLCP session复用

2023-02-24 23:30 UTC, superajun-wsj commented
> 缺少测试用例。包括
> 
> * TLCP 密码套件协商
> * TLCP SNI
> * TLCP ALPN
> * TLCP session复用

这个patch太大了，TLCP SNI/TLCP ALPN放到下个patch合入吧

2023-02-27 03:17 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/AbstractSessionContext.java
> +        this.enableTlcp = enableTlcp;
tlcp的ctx也支持通用ctx的功能吗？如果tlcp的ctx只能用于tlcp，为什么取名为enableTlcp而不是isTlcp

2023-02-27 03:17 UTC, Sere-Fu commented on openjdk/src/main/java/net/tongsuo/TlcpKeyManagerFactoryImpl.java
> +                    throw new KeyStoreException(e);
要不咱一起改成 ｜

2023-02-27 03:17 UTC, Sere-Fu commented on openjdk/src/main/java/net/tongsuo/TongsuoProvider.java
> +        put("X509ExtendedKeyManager.TlcpKeyManager", TlcpKeyManagerImpl.class.getName());
x509extendkeymanager这个类，貌似没有getInstance接口，也需要注册码？

2023-02-27 06:03 UTC, superajun-wsj commented on testing/src/main/java/org/conscrypt/TestUtils.java
> +        Base64.Decoder base64Decoder = Base64.getDecoder();
兼容性更好，在JDK8和JDK11上都可以跑

2023-02-27 06:04 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/AbstractSessionContext.java
> +    volatile long sslCtxNativePointer;
后面在if...else...里面根据条件判断进行优化

2023-02-27 06:05 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/AbstractSessionContext.java
> +        this.enableTlcp = enableTlcp;
很多类都是可以复用的，区别就在于是否enableTlcp.

2023-02-27 06:50 UTC, superajun-wsj commented on openjdk/src/main/java/net/tongsuo/TlcpKeyManagerFactoryImpl.java
> +                    throw new KeyStoreException(e);
Done

2023-02-27 06:50 UTC, superajun-wsj commented on openjdk/src/main/java/net/tongsuo/TongsuoProvider.java
> +        put("X509ExtendedKeyManager.TlcpKeyManager", TlcpKeyManagerImpl.class.getName());
这个不用注册，removed

2023-02-27 06:53 UTC, Sere-Fu approved these changes

2023-02-28 08:32 UTC, dongbeiouba requested changes

2023-02-28 09:35 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SSLParametersImpl.java
> +    // if the peer with this parameters allowed to creat new SSL session
Done

2023-02-28 09:35 UTC, superajun-wsj commented on openjdk/src/main/java/net/tongsuo/TongsuoProvider.java
> +        // put("X509ExtendedKeyManager.TlcpKeyManager", TlcpKeyManagerImpl.class.getName());
这个类不需要注册

2023-02-28 09:36 UTC, superajun-wsj commented on openjdk/src/test/java/org/conscrypt/TlcpDoubleCertTest.java
> +//      TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX");
先放在这里作为一个提示，下个patch还需要修改的

2023-02-28 09:39 UTC, superajun-wsj commented on openjdk/src/test/java/org/conscrypt/TlcpDoubleCertTest.java
> +//      TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
同上

2023-02-28 09:58 UTC, superajun-wsj commented on openjdk/src/test/java/org/conscrypt/TlcpDoubleCertTest.java
> +        // There is no support for SM2WithSM3,
Done

2023-02-28 10:00 UTC, superajun-wsj commented on CAPABILITIES.md
> +  * `ECC-SM2-WITH-SM4-SM3`
现在的实现可以支持这种别名，留着兼容性更好点

2023-02-28 10:00 UTC, superajun-wsj commented on CAPABILITIES.md
> +  * `ECDHE-SM2-WITH-SM4-SM3`
同上

2023-03-01 02:18 UTC, dongbeiouba approved these changes
LGTM

2023-03-01 02:20 UTC, merged