Add SM3 (Digest&HMac) support
Tongsuo-Project/tongsuo-java-sdk pull request #14
Opened 2023-02-07 06:42 UTC by Sere-Fu

2023-02-10 02:31 UTC, dongbeiouba requested changes

2023-02-10 02:31 UTC, dongbeiouba commented on common/src/test/resources/crypto/macs.csv
> +HmacSM3,65766572796f6e65,4861766520796f752065766572206265656e20746f206b616e6773616e202d2d2057656e6a756e204675,f09d8206335a66e7d9311ddaa4ab893609e3c7b783f3ea7300e5602bc2e68906
测试数据来自于哪里？注释一下吧

2023-02-10 02:38 UTC, Sere-Fu commented on common/src/test/resources/crypto/macs.csv
> +HmacSM3,65766572796f6e65,4861766520796f752065766572206265656e20746f206b616e6773616e202d2d2057656e6a756e204675,f09d8206335a66e7d9311ddaa4ab893609e3c7b783f3ea7300e5602bc2e68906
key和mess分别是两个字符串（我自己随便取的，已有的例子也是随便取的字符串）的ascii码。

2023-02-10 03:04 UTC, Sere-Fu commented on common/src/test/resources/crypto/macs.csv
> +HmacSM3,65766572796f6e65,4861766520796f752065766572206265656e20746f206b616e6773616e202d2d2057656e6a756e204675,f09d8206335a66e7d9311ddaa4ab893609e3c7b783f3ea7300e5602bc2e68906
加上注释了

2023-02-13 02:22 UTC, dongbeiouba approved these changes
LGTM

2023-02-14 08:09 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/OpenSSLMac.java
> +    public static final class HmacSM3 extends Hmac {
有的，在common/src/test/resources/crypto/macs.csv中添加了测试用例

2023-02-14 08:12 UTC, superajun-wsj approved these changes
LGTM

2023-02-14 08:13 UTC, merged