Add SM4 (CBC/CTR/ECB/CFB/OFB) support
Tongsuo-Project/tongsuo-java-sdk pull request #18
Opened 2023-02-15 06:06 UTC by Sere-Fu

SM4 测试用例拷贝自原本的AES-128测试用例（key，iv，input），输出由python的cryptography包计算得出。

2023-02-15 08:20 UTC, superajun-wsj commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +        cipher = EVP_sm4_ofb();
sm4好像也有GCM模式的？

2023-02-15 08:22 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/OpenSSLProvider.java
> +        put("Alg.Alias.AlgorithmParameters.1.2.156.10197.6.1.1.2", "AES");
这个OID号表示的是AES吗？

2023-02-15 08:30 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM4Cipher.java
> +            case PKCS5PADDING:
是不是也支持PKCS7Padding?

2023-02-15 08:31 UTC, superajun-wsj commented on common/src/test/java/org/conscrypt/javax/crypto/CipherBasicsTest.java
> +        BASIC_CIPHER_TO_TEST_DATA.put("SM4/CTR/NoPadding", "crypto/sm4-ctr.csv");
还有几种模式没有测试到？

2023-02-15 11:46 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/OpenSSLProvider.java
> +        put("Alg.Alias.AlgorithmParameters.1.2.156.10197.6.1.1.2", "AES");
这里我忘了改了，已经修复。

2023-02-15 11:47 UTC, Sere-Fu commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +        cipher = EVP_sm4_ofb();
先支持5种non aead的模式，gcm和ccm这两个aead的接口稍微不同，我后面单独一个patch支持。

2023-02-15 11:48 UTC, Sere-Fu commented on common/src/test/java/org/conscrypt/javax/crypto/CipherBasicsTest.java
> +        BASIC_CIPHER_TO_TEST_DATA.put("SM4/CTR/NoPadding", "crypto/sm4-ctr.csv");
同上

2023-02-15 11:50 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM4Cipher.java
> +            case PKCS5PADDING:
支持，conscrypt把pkcs7作为pkcs5的alias。所以实际上，用户request pkcs7的时候后台是生成pkcs5。

2023-02-15 11:51 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM4Cipher.java
> +            case PKCS5PADDING:
pkcs7和pkcs5 padding的方式是一样的，只是pkcs5规定block size为64，前者无限制。这两个名词经常不严格区分。

2023-02-16 02:08 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM4Cipher.java
> +            case PKCS5PADDING:
具体实现可以同一份，最好也把PKCS7Padding模式暴露给用户

2023-02-16 02:12 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM4Cipher.java
> +            case PKCS5PADDING:
PKCS7Padding已经暴露了的，provider类里面注册过。

2023-02-16 02:34 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM4Cipher.java
> +            case PKCS5PADDING:
OK

2023-02-16 05:47 UTC, superajun-wsj approved these changes
LGTM

2023-02-20 09:30 UTC, dongbeiouba requested changes
增加的csv测试用例建议参考Tongsuo项目test/recipes/30-test_evp_data/evpciph_sm4.txt文件，并标明出处

2023-02-20 10:46 UTC, Sere-Fu commented
> 增加的csv测试用例建议参考Tongsuo项目test/recipes/30-test_evp_data/evpciph_sm4.txt文件，并标明出处

Tongsuo中的测试条目加入csv中了

2023-02-21 02:02 UTC, dongbeiouba approved these changes
LGTM

2023-02-21 02:03 UTC, merged