Add SM2(Signature&Cipher) Support
Tongsuo-Project/tongsuo-java-sdk pull request #19
Opened 2023-02-20 09:35 UTC by Sere-Fu

2023-02-25 13:43 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +    {
保持风格一致，"{" 放到上一行末尾

2023-02-25 13:45 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +        }
为这些魔鬼数字加上注释

2023-02-25 13:48 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +        if (params != null) {
AlgorithmParameterSpec 当前都不支持吗？

2023-02-25 13:48 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            throw new InvalidAlgorithmParameterException("unknown param type: "
同上

2023-02-25 14:02 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +        byte[] output = new byte[engineGetOutputSize(buffer.size())];
可以探索下JNI调用导致的内存拷贝，是否可以考虑用堆外内存进行优化呢？

2023-02-25 14:03 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            throw new InvalidKeyException(e);
用"|"把这些异常类型连起来

2023-02-25 14:06 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            }
感觉用switch case风格更优雅？

2023-02-25 14:33 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            throw new InvalidKeyException(e);
这个是因为我看项目里目前的代码都没有使用 “｜”这个符号，我保持一致就连用多个catch。

2023-02-25 14:35 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +        if (params != null) {
不是不支持，SM2用来加密的时候并不需要传入参数

2023-02-25 14:36 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            throw new InvalidAlgorithmParameterException("unknown param type: "
同上

2023-02-25 15:04 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            }
这个也是因为和以后的rsacipher保持风格统一

2023-02-25 16:03 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +        byte[] output = new byte[engineGetOutputSize(buffer.size())];
整个buffer是一次性送进去tongsuo的 所以jni次数没法省。是说用directbuffer省内存拷贝吗？我想非对称加密一般数据不多 再者省下来的时间 相对加密本身（应该）是微不足道的。 加上项目本身类似地方都是用的堆内的，不如之后有必要升级性能再一口气重构buffer使用。

2023-02-26 12:57 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            }
打错字了，和已有的

2023-02-26 12:59 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +        }
已添加注释

2023-02-26 12:59 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +    {
已修改

2023-02-27 02:19 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            throw new InvalidKeyException(e);
可能之前比较老的JVM不支持这种用法，但JDK8之后应该都是支持的，建议修改成新风格

2023-02-27 02:29 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2KeyFactory.java
> +        }
what about ending with `else` ?

2023-02-27 02:29 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2KeyFactory.java
> +        throw new InvalidKeySpecException("Must use SM2PrivateKeySpec or PKCS8EncodedKeySpec; was "
同上

2023-02-27 02:39 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +        byte[] output = new byte[engineGetOutputSize(buffer.size())];
OK

2023-02-27 03:20 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +            throw new InvalidKeyException(e);
ok

2023-02-27 03:21 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2KeyFactory.java
> +        }
改好了

2023-02-27 03:21 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2KeyFactory.java
> +        throw new InvalidKeySpecException("Must use SM2PrivateKeySpec or PKCS8EncodedKeySpec; was "
改好了

2023-02-27 03:29 UTC, superajun-wsj approved these changes
LGTM

2023-02-28 03:39 UTC, dongbeiouba requested changes

2023-02-28 03:39 UTC, dongbeiouba commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +    protected int engineGetOutputSize(int inputLen) {
建议调用Tongsuo EVP_PKEY_encrypt()接口获取输出长度，屏蔽底层细节

2023-02-28 03:39 UTC, dongbeiouba commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +    protected int engineGetOutputSize(int inputLen) {
建议调用Tongsuo EVP_PKEY_encrypt()接口获取输出长度，屏蔽底层细节

2023-02-28 03:43 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +    protected int engineGetOutputSize(int inputLen) {
java直接算很快，调用tongsuo要走jni开销比较大。

2023-02-28 03:45 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +    protected int engineGetOutputSize(int inputLen) {
主要是因为java直接算很快，调用tongsuo要多走一次jni开销比较大。

2023-02-28 03:45 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/SM2Cipher.java
> +    protected int engineGetOutputSize(int inputLen) {
同

2023-02-28 09:28 UTC, dongbeiouba approved these changes
LGTM

2023-02-28 09:28 UTC, merged