2022122301 cert 1
Tongsuo-Project/tongsuo-java-sdk pull request #2
Opened 2022-12-23 08:43 UTC by lukang-zlh

submit public key reading and test case

2022-12-23 08:44 UTC, lukang-zlh commented
@dongbeiouba 请帮忙review

2022-12-26 07:22 UTC, dongbeiouba requested changes
没有看到TLS 1.3 + 商密套件 握手的测试用例

2022-12-26 07:22 UTC, dongbeiouba commented on common/src/test/java/org/conscrypt/javax/net/ssl/SSLSocketTest.java
> +        assertNotSame(enabledCipherSuites, currentEnabledCipherSuites);
set和get获取的套件应该不一样？不是应该一样才对吗

2022-12-26 07:22 UTC, dongbeiouba commented on common/src/test/java/org/conscrypt/javax/net/ssl/SSLSocketTest.java
> +    public void test_SSLSocket_setEnabledCipherSuites_SM2() throws Exception {
建议改一下名字，test_SSLSocket_setEnabledCipherSuites_SM2 -> test_SSLSocket_setEnabledCipherSuites_ ShangMi

2022-12-26 07:22 UTC, dongbeiouba commented on openjdk/src/test/java/org/conscrypt/OpenSSLX509CertificateTest.java
> +    public void test_GenECPrivateKey()throws Exception{
建议改一下名字，test_GenECPrivateKey -> test_LoadSM2PrivateKey

2022-12-26 07:22 UTC, dongbeiouba commented on openjdk/src/test/java/org/conscrypt/OpenSSLX509CertificateTest.java
> +    public void test_BuildSSLCertificatChain()throws Exception{
建议改名字，test_BuildSSLCertificatChain -> test_BuildSM2CertificatChain

2022-12-26 07:22 UTC, dongbeiouba commented on openjdk/src/test/resources/ca-root-sm2.crt
> +-----BEGIN CERTIFICATE-----
这个证书不是root CA，是不是上传了错误的证书？

2022-12-26 07:22 UTC, dongbeiouba commented on openjdk/src/test/resources/ca-sub-sm2.crt
> +-----BEGIN CERTIFICATE-----
这个是根CA证书，不是sub ca

2022-12-26 07:22 UTC, dongbeiouba commented on testing/src/main/java/org/conscrypt/TestUtils.java
> +        InputStream inputStream = openTestFile("test-sm2-private.key");
hard code "test-sm2-private.key"? 应该是name吧

2022-12-26 07:22 UTC, dongbeiouba commented on testing/src/main/java/org/conscrypt/TestUtils.java
> +    public static PrivateKey readPrivateKeyPemFile(String name)throws Exception{
建议改名字，readPrivateKeyPemFile -> readSM2PrivateKeyPemFile

2023-01-03 07:38 UTC, closed without merging