Add Aead(GCM/CCM) Support For SM4
Tongsuo-Project/tongsuo-java-sdk pull request #23
Opened 2023-03-06 08:47 UTC by Sere-Fu

2023-03-08 04:06 UTC, superajun-wsj commented on common/src/test/java/org/conscrypt/javax/crypto/AeadCipherTest.java
> +      "SM4/GCM/NoPadding",
为啥注释掉了这三个测试用例？

2023-03-08 05:57 UTC, Sere-Fu commented on common/src/test/java/org/conscrypt/javax/crypto/AeadCipherTest.java
> +      "SM4/GCM/NoPadding",
aes和chacha的aead模式之前的patch删掉了，这个commit只关注sm4。

2023-03-08 06:59 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/CCMParameterSpec.java
> +        this.icvLen = icvLen;
等第二组参数检测通过再赋值行吗？

2023-03-08 07:02 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/CCMParameterSpec.java
> +        this.icvLen = icvLen;
可以哇，我是觉得写在一起好看点，这个没啥开销

2023-03-08 07:34 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
> +    private boolean arraysAreEqual(byte[] a, byte[] b) {
这个方法需要自己实现吗？用JDK自带的Arrays.equals是否可行？

2023-03-08 07:58 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
> +    private boolean arraysAreEqual(byte[] a, byte[] b) {
假设两个array长度均为16，且前8个byte相同，后面开始不通。自带的Array.equals

2023-03-08 07:58 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
> +    private boolean arraysAreEqual(byte[] a, byte[] b) {
假设两个array长度均为16，且前8个byte相同，后面开始不通。自带的Array.equals

2023-03-08 08:00 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
> +    private boolean arraysAreEqual(byte[] a, byte[] b) {
假设两个array长度均为16，且前8个byte相同，后面开始不通。自带的Array.equals会在第9个byte匹配失败就返回false，而这个自己实现的固定要走完整个array。这样避免了通过函数返回时间来猜测密钥。

2023-03-08 08:01 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
> +    private boolean arraysAreEqual(byte[] a, byte[] b) {
OK

2023-03-09 04:19 UTC, dongbeiouba requested changes

2023-03-09 04:19 UTC, dongbeiouba commented on examples/jce/CipherExample.java
> +    private static void asymmetricExample(byte[] input) throws Exception {
建议SM2示例单独搞一个文件，跟SM4分开

2023-03-09 04:19 UTC, dongbeiouba commented on examples/jce/MessageDigestExample.java
> +import java.security.MessageDigest;
文件名上带上SM3，方便查找

2023-03-09 04:19 UTC, dongbeiouba commented on examples/jce/SignatureExample.java
> +import java.security.KeyPair;
文件名字上带上SM2，方便查找

2023-03-09 04:19 UTC, dongbeiouba commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    UniquePtr<EVP_CIPHER_CTX> ctx(EVP_CIPHER_CTX_new());
同上

2023-03-09 04:19 UTC, dongbeiouba commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    UniquePtr<EVP_CIPHER_CTX> ctx(EVP_CIPHER_CTX_new());
ctx释放需要调用EVP_CIPHER_CTX_free()

2023-03-09 04:19 UTC, dongbeiouba commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    UniquePtr<EVP_CIPHER_CTX> ctx(EVP_CIPHER_CTX_new());
同上

2023-03-09 06:26 UTC, Sere-Fu commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    UniquePtr<EVP_CIPHER_CTX> ctx(EVP_CIPHER_CTX_new());
把ctx_free注册过的，会自动调用

2023-03-09 06:26 UTC, Sere-Fu commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    UniquePtr<EVP_CIPHER_CTX> ctx(EVP_CIPHER_CTX_new());
同

2023-03-09 06:26 UTC, Sere-Fu commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    UniquePtr<EVP_CIPHER_CTX> ctx(EVP_CIPHER_CTX_new());
同

2023-03-09 06:26 UTC, Sere-Fu commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +    UniquePtr<EVP_CIPHER_CTX> ctx(EVP_CIPHER_CTX_new());
同

2023-03-09 06:27 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/CCMParameters.java
> +/*
讨论过，暂时不变位置

2023-03-09 07:41 UTC, dongbeiouba approved these changes
LGTM

2023-03-09 07:44 UTC, superajun-wsj commented
LGTM

2023-03-09 07:44 UTC, superajun-wsj approved these changes
LGTM

2023-03-09 07:44 UTC, superajun-wsj approved these changes
LGTM

2023-03-09 07:45 UTC, merged