Add ChaCha20(&Poly1305) Support
Tongsuo-Project/tongsuo-java-sdk pull request #26
Opened 2023-03-30 07:04 UTC by Sere-Fu

2023-04-04 02:45 UTC, superajun-wsj approved these changes
LGTM

2023-04-10 09:55 UTC, dongbeiouba requested changes

2023-04-10 09:55 UTC, dongbeiouba commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +
缺少EVP_CipherFinal()

2023-04-10 09:55 UTC, dongbeiouba commented on common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
> +                    throw new InvalidAlgorithmParameterException("Must be CCMParameterSpec");
CCMParameterSpec ??

2023-04-11 02:44 UTC, Sere-Fu commented on common/src/jni/main/cpp/conscrypt/native_crypto.cc
> +
补上了

2023-04-11 02:44 UTC, Sere-Fu commented on common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
> +                    throw new InvalidAlgorithmParameterException("Must be CCMParameterSpec");
fixed

2023-04-19 07:02 UTC, merged