the ShangMi cipher suites supports tls1.3 communication
Tongsuo-Project/tongsuo-java-sdk pull request #4
Opened 2023-01-03 03:53 UTC by lukang-zlh

@dongbeiouba 请帮忙review

2023-01-03 08:13 UTC, dongbeiouba requested changes

2023-01-03 08:13 UTC, dongbeiouba commented on common/src/test/java/org/conscrypt/javax/net/ssl/SSLSocketTest.java
> +        return (SSLServerSocket)socketFactory.createServerSocket(8888);
如果系统已经监听8888端口，会导致监听失败。是不是可以使用TestSSLSocketPair代替？或者使用类似createServerSocket(0)之类的代替

2023-01-04 03:44 UTC, dongbeiouba approved these changes
LGTM，merge前把2个commit合并成一个吧

2023-01-04 03:55 UTC, superajun-wsj commented
LGTM

2023-01-04 04:03 UTC, superajun-wsj approved these changes

2023-01-04 04:19 UTC, merged