expoort tongsuo-java-sdk's provider as net.tongsuo
Tongsuo-Project/tongsuo-java-sdk pull request #6
Opened 2023-01-06 09:02 UTC by superajun-wsj

2023-01-09 04:12 UTC, dongbeiouba requested changes

2023-01-09 04:12 UTC, dongbeiouba commented on openjdk/src/test/java/net/tongsuo/TongsuoProviderEndToEndTest.java
> + * Copyright (C) 2010 The Android Open Source Project
Copyright问题，同上

2023-01-09 04:12 UTC, dongbeiouba commented on openjdk/src/test/resources/cert/server.crt
> +-----BEGIN CERTIFICATE-----
已经存在测试用的sm2证书，考虑复用

2023-01-09 04:12 UTC, dongbeiouba commented on openjdk/src/test/resources/cert/server.key
> +-----BEGIN EC PARAMETERS-----
已经存在测试用的SM2私钥，考虑复用

2023-01-09 04:12 UTC, dongbeiouba commented on openjdk/src/test/java/net/tongsuo/TongsuoProviderEndToEndTest.java
> +    private final String PRIVATE_KEY = "-----BEGIN EC PRIVATE KEY-----\n"
建议改成使用文件，而不是内容直接放到代码中

2023-01-11 08:55 UTC, superajun-wsj commented on openjdk/src/test/resources/cert/server.crt
> +-----BEGIN CERTIFICATE-----
不在同一个工程，在运行test的时候无法访问到的

2023-01-11 08:55 UTC, superajun-wsj commented on openjdk/src/test/java/net/tongsuo/TongsuoProviderEndToEndTest.java
> + * Copyright (C) 2010 The Android Open Source Project
Done

2023-01-11 08:55 UTC, superajun-wsj commented on openjdk/src/main/java/net/tongsuo/TongsuoX509Certificate.java
> + * Copyright (C) 2017 The Android Open Source Project
Done

2023-01-11 08:56 UTC, superajun-wsj commented on openjdk/src/main/java/net/tongsuo/TongsuoProvider.java
> + * Copyright (C) 2017 The Android Open Source Project
Done

2023-01-11 11:04 UTC, superajun-wsj commented on openjdk/src/test/java/net/tongsuo/TongsuoProviderEndToEndTest.java
> +    private final String PRIVATE_KEY = "-----BEGIN EC PRIVATE KEY-----\n"
Done

2023-01-11 11:04 UTC, superajun-wsj commented on openjdk/src/test/resources/cert/server.key
> +-----BEGIN EC PARAMETERS-----
同上

2023-01-11 11:18 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/OpenSSLProvider.java
> +                        "Choice of default protocol is unsupported: " + defaultTlsProtocol);
Done

2023-01-11 11:18 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/OpenSSLProvider.java
> +                "AES_128/GCM-SIV/NoPadding", "OpenSSLAeadCipherAES$GCM_SIV$AES_128");
Done

2023-01-11 11:20 UTC, superajun-wsj commented on common/src/main/java/org/conscrypt/OpenSSLProvider.java
> +                                                String fullyQualifiedClassName,
Done

2023-01-12 09:27 UTC, dongbeiouba approved these changes
LGTM

2023-01-14 03:31 UTC, dongbeiouba commented
ping @InfoHunter @lukang-zlh @yuleil @Sere-Fu

2023-01-17 02:27 UTC, Sere-Fu approved these changes
LGTM

2023-01-17 02:37 UTC, merged